/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-05-31 04:34:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import model.StudentDAO;
import model.Student;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Index page</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("\n");
      out.write("<!-- Latest compiled and minified CSS -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<!-- Date picker -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.1/css/bootstrap-datepicker.css\">\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.1/js/bootstrap-datepicker.js\"></script>\n");
      out.write("\n");

	StudentDAO studentDao = new StudentDAO();

	List<Student> students = null;

	String searchKey = request.getParameter("key");
	if (searchKey != null && searchKey != "") {
		students = studentDao.searchStudent(searchKey);
	} else {
		students = studentDao.getStudentList();
	}

	int pageNum = (int) Math.ceil((double) students.size() / 5);

	int currentPage;
	if (request.getParameter("page") != null && request.getParameter("page") != "") {
		currentPage = Integer.parseInt(request.getParameter("page"));
	} else {
		currentPage = 1;
	}

      out.write("\n");
      out.write("<body>\n");
      out.write("\t<h1 class=\"text-center\">Student Management</h1>\n");
      out.write("<hr/>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<form class=\"form-horizontal col-md-8 col-md-offset-3\" action=\"home\"\n");
      out.write("\t\t\tmethod=\"get\">\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search...\"\n");
      out.write("\t\t\t\t\t\trequired name=\"key\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" type=\"submit\">Search</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\n");
      out.write("\t\t<table class=\"table table-striped table-bordered\">\n");
      out.write("\t\t\t<thead>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th class=\"text-center\">ID</th>\n");
      out.write("\t\t\t\t\t<th class=\"text-center\">First Name</th>\n");
      out.write("\t\t\t\t\t<th class=\"text-center\">Last Name</th>\n");
      out.write("\t\t\t\t\t<th class=\"text-center\">Birth Date</th>\n");
      out.write("\t\t\t\t\t<th class=\"text-center\">Update/Delete</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</thead>\n");
      out.write("\t\t\t<tbody>\n");
      out.write("\t\t\t\t");

					if (students.size() > 0) {
						int startIndex = currentPage * 5 - 5;
						int endIndex;
						if (currentPage < pageNum) {
							endIndex = currentPage * 5;
						} else {
							endIndex = students.size();
						}
						for (int i = startIndex; i < endIndex; i++) {
							Student student = students.get(i);
				
      out.write("\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"text-center\">");
      out.print(student.getId());
      out.write("</td>\n");
      out.write("\t\t\t\t\t<td>");
      out.print(student.getFirstName());
      out.write("</td>\n");
      out.write("\t\t\t\t\t<td>");
      out.print(student.getLastName());
      out.write("</td>\n");
      out.write("\t\t\t\t\t<td class=\"text-center\">");
      out.print(new SimpleDateFormat("dd/MM/yyyy").format(student.getBirthDate()));
      out.write("</td>\n");
      out.write("\t\t\t\t\t<td class=\"text-center\"><a\n");
      out.write("\t\t\t\t\t\thref=\"delete?id=");
      out.print(student.getId());
      out.write("\"\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-remove\"></a> <a\n");
      out.write("\t\t\t\t\t\thref=\"edit?id=");
      out.print(student.getId());
      out.write("\"\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil\"></a></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<ul class=\"pagination\">\n");
      out.write("\t\t\t");

				for (int i = 1; i <= pageNum; i++) {
			
      out.write("\n");
      out.write("\t\t\t<li><a href=\"home?page=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<hr/>\n");
      out.write("\t\t<h1 class=\"text-center\">Insert Student</h1>\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<form class=\"form col-md-6 col-md-offset-3\" action=\"addStudent\"\n");
      out.write("\t\t\t\tmethod=\"post\">\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label>First Name: </label> <input class=\"form-control\" type=\"text\"\n");
      out.write("\t\t\t\t\t\trequired name=\"firstName\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label>Last Name: </label> <input class=\"form-control\" type=\"text\"\n");
      out.write("\t\t\t\t\t\trequired name=\"lastName\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label>Birth Date:</label> <input name=\"birthDate\" type=\"text\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" required id=\"datepicker\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group-btn\">\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" type=\"submit\">Add</button>\n");
      out.write("\t\t\t\t\t<button class=\"btn\" type=\"reset\">Clear</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(\"#datepicker\").datepicker({\n");
      out.write("\t\t\tformat : 'dd/mm/yyyy'\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
